# Generated by Django 5.1.2 on 2024-10-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Введите название страны",
                        max_length=60,
                        verbose_name="County",
                    ),
                ),
                (
                    "tin",
                    models.CharField(
                        help_text="Введите ИНН",
                        max_length=20,
                        verbose_name="Tax Identification Number",
                    ),
                ),
                (
                    "address",
                    models.TextField(help_text="Введите адрес", verbose_name="Address"),
                ),
            ],
            options={
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
            },
        ),
    ]
