# Generated by Django 5.1.2 on 2024-10-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="country",
            field=models.CharField(
                help_text="Введите название страны",
                max_length=60,
                verbose_name="Country",
            ),
        ),
    ]
