# Generated by Django 5.1.2 on 2024-11-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_category_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "price", "updated_at"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Опубликовать продукт",
                verbose_name="Статус публикации",
            ),
        ),
    ]
